---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# onRobs

<!-- badges: start -->
<!-- badges: end -->

This package enables you to control OBS through the OBS Websockets Server. Its strongly rely on the [websocket package](https://cran.r-project.org/web/packages/websocket/index.html).

If you are new here, check the [Get started](https://franklentz.github.io/onRobs/articles/onRobs.html) page. 

## Installation

You can install the development version of onRobs from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("franklentz/onRobs")
```

## Example



```{r example}
library(onRobs)

# myobs <- createOBSWebsocket() 
# connectToOBS(obs = myobs)
# identifyToOBS(obs = myobs, eventSub = "33", password = "myObsWebsocketsServerPassword")
# CreateScene(obs = myobs, sceneName = "New Scene")
# SetCurrentProgramScene(obs = myobs, scene = "Muti Cam Scene")
# SetCurrentProgramScene(obs = myobs, scene = "BRB")
# disconnectFromOBS(myobs)
```

